server:
  port: ${APP_PORT:8080}
  servlet:
    encoding:
      charset: "UTF-8"
      force: true
spring:
  webflux:
    base-path: /api/v1/tax
  application:
    name: taxes-demo
  devtools:
    add-properties: false
  profiles:
    active: ${ENV:local}
  #r2dbc:
  #  url: ""  # Desactiva la configuración automática
management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "health"
        liveness: "liveness"
        readiness: "readiness"
      exposure:
        include: "health, liveness, readiness, metrics"
        #include: "*"
  endpoint:
    health:
      show-details: "never"
      cache:
        time-to-live: "10s"
      probes:
        enabled: true
logging:
  level:
    root: ${ROOT_LEVEL_LOG:info}
    web: ${LOG4J_LEVEL:info}
r2dbc:
  mysql:
      #url: ${MYSQL_URL:r2dbc:mysql://localhost:3306/taxes_Demo}
      username: ${MYSQL_USER:user}
      password: ${MYSQL_PASSWORD:demo}
      port: ${MYSQL_PORT:3306}
      host: ${MYSQL_HOST:localhost}
      database: ${MYSQL_DATABASE:taxes_Demo}
      pool:
        initial-size: 5  # Número inicial de conexiones en el pool
        max-size: 20      # Número máximo de conexiones en el pool
        max-idle-time: 30m # Tiempo máximo de inactividad de una conexión
        validation-query: "SELECT 1" # Consulta para validar conexiones

rest-consumer:
  timeout:
    default-connection: ${REST_TIMEOUT_CONNECTION:3000}
    default-read: ${REST_TIMEOUT_READ:3000}
    default-write: ${REST_TIMEOUT_WRITE:3000}
  api-calendar:
    baseUrl: https://api.generadordni.es
    #baseUrl: http://localhost:3004
    holiday: /v2/holidays/holidays #/v2/holidays/holidays?country=ES&year=2025
    connectTimeout: ${API_CALENDAR_CONNECT_TIMEOUT:3000}
    responseTimeout: ${API_CALENDAR_RESPONSE_TIMEOUT:3000}
    apiKey: ${API_CALENDAR_KEY:xxxxx}

error-status-mapper:
  default-status: 500